### ISSUE TITLE
Github Actions problem with final upload of the artefact if H.264 or X11 is defined

### ISSUE THREAD

**Issue by neilyoung** [crow-misia/libmediasoup-android#17]
Since I'm just concentrating on Android at the moment, I can just report a problem for this build.

Symptom: The upload of the final artefact fails, because the GH script tries to upload a package which doesn't exist:

<img width="1105" alt="image" src="https://github.com/crow-misia/libmediasoup-android/assets/731020/54e68e58-5c2f-4261-a524-33f8b771e7b0">

Reason: 

In `libwebrtc-bin/build/common.mk` there is some magic applied to the package name, depending on whether H264 and/or X11 is defined. The final upload doesn't take that possible renaming in account.

**libwebrtc-bin/build/common.mk**:

```
PACKAGE_NAME := libwebrtc

ifneq (x$(TARGET_OS),x)
PACKAGE_NAME += -$(TARGET_OS)
endif
ifneq (x$(TARGET_CPU),x)
PACKAGE_NAME += -$(TARGET_CPU)
endif

ifeq ($(USE_H264),1)
RTC_USE_H264 := rtc_use_h264=true
PACKAGE_NAME += -h264
else
RTC_USE_H264 := rtc_use_h264=false
endif

ifeq ($(USE_X11),1)
RTC_USE_X11 := rtc_use_x11=true
PACKAGE_NAME += -x11
else
RTC_USE_X11 := rtc_use_x11=false
endif

```

Leads to a package `libwebrtc-android-h264.tar.xz`. The upload tries to upload `libwebrtc-android.tar.xz`

**libwebrtc-bin/.github/workflows/build.yml**:

```
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: libwebrtc-${{ matrix.name }}.tar.xz
          path: package/libwebrtc-${{ matrix.name }}.tar.xz
```
